spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        service: ${spring.application.name}
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        import-check:
          enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 2

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:rabbitmq}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        concurrency: 8
        max-concurrency: 16
        prefetch: 8

dubbo:
  application:
    name: ${spring.application.name}-dubbo
    qos-enable: false
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
    register-mode: instance
  consumer:
    timeout: 3000
    check: false
  protocol:
    name: dubbo
    port: -1

gateway:
  port: 75